source "http://rubygems.org"

group :development, :test do
  gem 'rake'
  gem 'builder'
  gem 'cucumber'
  gem 'diff-lcs'
  gem 'eventmachine'
  gem 'freeswitcher'
  gem 'gherkin'
  gem 'gist'
  gem 'json'
  gem 'log4r'
  gem 'nokogiri'
  gem 'rack'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'term-ansicolor'
  gem 'webrat'
  gem 'ZenTest'
  gem 'autotest'

  # Adding pry for debugging
  gem 'ruby-debug19'
  gem 'ruby-debug-ide19'
  gem 'pry'
  gem 'pry-doc'
  gem 'pry_debug'
  gem 'pry-nav'
  gem 'pry-stack_explorer'
  gem 'pry-exception_explorer'
  gem 'ruby-debug-pry'
  gem 'plymouth'
end
